export const GET_INFO_ABOUT_CAR = "GET_INFO_ABOUT_CAR"

export const GET_ICONS_ABOUT_CAR = "GET_ICONS_ABOUT_CAR"

export const UPDATE_ABOUT_CAR = "UPDATE_ABOUT_CAR"

export const CHANGE_OPTION_SELECT = "CHANGE_OPTION_SELECT/ABOUT_CAR"

export const CHANGE_ICON_SELECT = "CHANGE_ICON_SELECT/ABOUT_CAR"

export const GET_NEXT_IMG_URL_SLIDER = "GET_NEXT_IMG_URL_SLIDER/ABOUT_CAR"

export const UPDATE_IMG_SLIDER = "UPDATE_IMG_SLIDER/ABOUT_CAR"
