export const GET_INFO_ABOUT_CAR = "GET_INFO_ABOUT_CAR"

export const GET_ICONS_BODY_SALON_ABOUT_CAR = "GET_ICONS_BODY_SALON_ABOUT_CAR"

export const UPDATE_ABOUT_CAR = "UPDATE_ABOUT_CAR"

export const CHANGE_OPTION_SELECT_BODY = "CHANGE_OPTION_SELECT_BODY/ABOUT_CAR"

export const CHANGE_ICON_SELECT_BODY_SALON = "CHANGE_ICON_SELECT_BODY/ABOUT_CAR"

export const GET_NEXT_IMG_URL_SLIDER = "GET_NEXT_IMG_URL_SLIDER/ABOUT_CAR"

export const UPDATE_IMG_SLIDER_BODY = "UPDATE_IMG_SLIDER_BODY/ABOUT_CAR"
