export const GET_CARS_JSON = "GET_CARS_JSON"

export const HANDLE_LOADER = "HANDLE_LOADER"

export const UPDATE_SLIDER_BODY_SALON = "UPDATE_SLIDER_BODY_SALON"

export const GET_IMG_URL_SLIDER_BODY_SALON = "GET_IMG_URL_SLIDER_BODY_SALON"

export const RESET_SLIDER = "RESET_SLIDER"

export const RESET_SLIDER_TYPE1 = "RESET_SLIDER_TYPE1"

export const GET_IMG_WIDGETS = "GET_IMG_WIDGETS"

export const UPDATE_WIDGETS_SELECT = "GET_IMG_WIDGETS_SELECT"

export const CHANGE_PREV_IMG_SLIDER = "CHANGE_PREV_IMG_SLIDER"