export const GET_CARS_JSON = "GET_CARS_JSON"

export const HANDLE_LOADER = "HANDLE_LOADER"

export const UPDATE_SLIDER_BODY_SALON = "UPDATE_SLIDER_BODY_SALON"

export const GET_IMG_URL_SLIDER_BODY_SALON = "GET_IMG_URL_SLIDER_BODY_SALON"


